version: "3.9"
services:
  auth:
    build: ../app-auth/.
    # to expose the auth service to the host machine, uncomment the following
    # ports:
    #   - "3001:3001"
  api-gateway:
    build: ../infra-api-gateway/.
    ports:
      - "8080:8080"
    volumes:
      - ../infra-api-gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
